#!/usr/bin/env bash
# Build llama.cpp with the Vulkan backend (via MoltenVK) on an Intel Mac.
#
# IMPORTANT: this pins llama.cpp to release tag b8142. Builds after b8142 have a
# known regression that makes Vulkan on Intel Macs (incl. the Radeon Pro 5600M)
# produce gibberish output:
#   https://github.com/ggml-org/llama.cpp/issues/20029
#   https://github.com/ggml-org/llama.cpp/issues/20104
# Once those are fixed upstream, unpin with: LLAMA_VULKAN_REF=master ./build-vulkan.sh
#
# Overridable environment variables:
#   LLAMA_WORKSPACE   where sources/builds/models live (default: ~/llama-macos-intel)
#   LLAMA_REPO        git repo to build from           (default: upstream ggml-org/llama.cpp)
#   LLAMA_VULKAN_REF  git branch/tag to build          (default: b8142 — see above)
set -euo pipefail

REPO="${LLAMA_REPO:-https://github.com/ggml-org/llama.cpp}"
REF="${LLAMA_VULKAN_REF:-b8142}"
ROOT="${LLAMA_WORKSPACE:-$HOME/llama-macos-intel}"
SRC="$ROOT/src-vulkan"
ENV_FILE="$ROOT/env-vulkan.sh"

say()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "This script must run on macOS."
xcode-select -p >/dev/null 2>&1 \
  || die "Xcode Command Line Tools not found. Install with: xcode-select --install"
command -v cmake >/dev/null 2>&1 \
  || die "cmake not found. Install with: brew install cmake"

mkdir -p "$ROOT" "$ROOT/models" "$ROOT/logs"

# ---------------------------------------------------------------------------
# Locate a Vulkan toolchain. Preferred: the LunarG Vulkan SDK (bundles
# MoltenVK + glslc). Fallback: Homebrew packages.
# ---------------------------------------------------------------------------
EXTRA_CMAKE_ARGS=()

if [[ -z "${VULKAN_SDK:-}" ]]; then
  # Try to auto-source the newest installed LunarG SDK.
  SETUP="$(ls -dt "$HOME"/VulkanSDK/*/setup-env.sh 2>/dev/null | head -1 || true)"
  if [[ -n "$SETUP" ]]; then
    say "Sourcing LunarG SDK environment: $SETUP"
    # shellcheck disable=SC1090
    source "$SETUP"
  fi
fi

if [[ -n "${VULKAN_SDK:-}" ]]; then
  say "Using LunarG Vulkan SDK at: $VULKAN_SDK"
  MODE="sdk"
elif command -v brew >/dev/null 2>&1 && brew --prefix molten-vk >/dev/null 2>&1; then
  say "No LunarG SDK found — using Homebrew Vulkan packages"
  MODE="brew"
  for pkg in molten-vk vulkan-headers vulkan-loader shaderc glslang; do
    brew --prefix "$pkg" >/dev/null 2>&1 \
      || die "Homebrew package '$pkg' missing. Install all with:
  brew install molten-vk vulkan-headers vulkan-loader shaderc glslang"
  done
  EXTRA_CMAKE_ARGS+=(
    "-DVulkan_INCLUDE_DIR=$(brew --prefix vulkan-headers)/include"
    "-DVulkan_LIBRARY=$(brew --prefix vulkan-loader)/lib/libvulkan.dylib"
    "-DVulkan_GLSLC_EXECUTABLE=$(brew --prefix shaderc)/bin/glslc"
    "-DVulkan_GLSLANG_VALIDATOR_EXECUTABLE=$(brew --prefix glslang)/bin/glslangValidator"
  )
else
  die "No Vulkan toolchain found. Either:
  1. (Recommended) Install the LunarG Vulkan SDK from https://vulkan.lunarg.com/sdk/home
     then run:  source ~/VulkanSDK/<version>/setup-env.sh  and re-run this script; or
  2. brew install molten-vk vulkan-headers vulkan-loader shaderc glslang"
fi

# ---------------------------------------------------------------------------
# Clone at the pinned ref and build.
# ---------------------------------------------------------------------------
if [[ -d "$SRC/.git" ]]; then
  say "Updating existing checkout at $SRC (ref: $REF)"
  git -C "$SRC" fetch --depth 1 origin "tag" "$REF" 2>/dev/null \
    || git -C "$SRC" fetch --depth 1 origin "$REF"
  git -C "$SRC" checkout -q FETCH_HEAD
else
  say "Cloning $REPO at pinned ref $REF into $SRC"
  git clone --depth 1 --branch "$REF" "$REPO" "$SRC"
fi

say "Configuring (Vulkan backend, Metal disabled for this build)"
cmake -S "$SRC" -B "$SRC/build" \
  -DCMAKE_BUILD_TYPE=Release \
  -DGGML_VULKAN=1 \
  -DGGML_METAL=OFF \
  "${EXTRA_CMAKE_ARGS[@]+"${EXTRA_CMAKE_ARGS[@]}"}"

say "Building (shader compilation makes this slower than the Metal build)"
cmake --build "$SRC/build" --config Release -j "$(sysctl -n hw.ncpu)"

BIN="$SRC/build/bin/llama-server"
[[ -x "$BIN" ]] || die "Build finished but $BIN is missing — check the output above."

# ---------------------------------------------------------------------------
# Write the runtime environment file that llama.sh sources before launching
# the Vulkan binary, so the MoltenVK driver is always found.
# ---------------------------------------------------------------------------
say "Writing runtime environment to $ENV_FILE"
if [[ "$MODE" == "sdk" ]]; then
  SDK_SETUP="$(ls -dt "$HOME"/VulkanSDK/*/setup-env.sh 2>/dev/null | head -1 || true)"
  cat > "$ENV_FILE" <<EOF
# Generated by build-vulkan.sh — sourced by llama.sh before running the Vulkan build.
if [[ -n "$SDK_SETUP" && -f "$SDK_SETUP" ]]; then
  source "$SDK_SETUP"
fi
export VK_ICD_FILENAMES="\${VULKAN_SDK}/share/vulkan/icd.d/MoltenVK_icd.json"
export VK_DRIVER_FILES="\$VK_ICD_FILENAMES"
EOF
else
  cat > "$ENV_FILE" <<EOF
# Generated by build-vulkan.sh — sourced by llama.sh before running the Vulkan build.
export VK_ICD_FILENAMES="$(brew --prefix molten-vk)/share/vulkan/icd.d/MoltenVK_icd.json"
export VK_DRIVER_FILES="\$VK_ICD_FILENAMES"
export DYLD_FALLBACK_LIBRARY_PATH="$(brew --prefix vulkan-loader)/lib:$(brew --prefix molten-vk)/lib:\${DYLD_FALLBACK_LIBRARY_PATH:-}"
EOF
fi

say "Done. Vulkan build (pinned to $REF) is at: $BIN"
say "Sanity check that your AMD GPU shows up with:"
say "  ./llama.sh vulkan --list-devices"
say "Then start chatting via: ./llama.sh vulkan -m <model.gguf>   (WebUI on http://127.0.0.1:8080)"
