/**
 * Localization for errors generated by commander itself.
 *
 * commander builds its error strings in English at call time (`error: unknown command 'x'`),
 * which is why wrapping the text our own code prints is not enough: argument validation, unknown
 * options and unknown subcommands never reach a `t()` call. They are rewritten at the one point
 * commander exposes for them — `configureOutput().outputError`.
 *
 * In English the original string is returned byte-for-byte, so non-Chinese output stays exactly
 * what upstream produces. An unrecognised shape is returned unchanged as well: a stale template
 * must degrade to English rather than silently mangle a real error.
 *
 * @public
 */

import type { CommandUnknownOpts } from "@commander-js/extra-typings";
import { getLocale, t } from "./i18n/index.js";

interface ErrorRule {
  /** Matches the raw commander message. */
  pattern: RegExp;
  /** Produces the English source (the lookup key) plus its `{placeholder}` values. */
  build: (match: RegExpMatchArray) => [string, Record<string, string>];
}

const RULES: Array<ErrorRule> = [
  {
    pattern: /^error: missing required argument '([^']+)'$/,
    build: m => [`error: missing required argument '{name}'`, { name: m[1] }],
  },
  {
    pattern:
      /^error: too many arguments for '(.+?)'\. Expected (\d+) argument(s?) but got (\d+)\.$/,
    build: m => [
      `error: too many arguments for '{command}'. Expected {expected} argument{s} but got {received}.`,
      // English marks the plural with `s`; Chinese has no plural morphology, so it renders empty.
      { command: m[1], expected: m[2], s: "", received: m[4] },
    ],
  },
  {
    pattern: /^error: too many arguments\. Expected (\d+) argument(s?) but got (\d+)\.$/,
    build: m => [
      `error: too many arguments. Expected {expected} argument{s} but got {received}.`,
      { expected: m[1], s: "", received: m[3] },
    ],
  },
  {
    pattern: /^error: unknown command '([^']+)'(.*)$/,
    build: m => [`error: unknown command '{name}'{suggestion}`, { name: m[1], suggestion: m[2] }],
  },
  {
    pattern: /^error: unknown option '([^']+)'(.*)$/,
    build: m => [`error: unknown option '{flag}'{suggestion}`, { flag: m[1], suggestion: m[2] }],
  },
  {
    // commander appends the parser's own reason: `... is invalid. 不是数字`
    pattern: /^error: option '(.+?)' argument '(.*)' is invalid\.(.*)$/,
    build: m => [
      `error: option '{option}' argument '{value}' is invalid.{reason}`,
      { option: m[1], value: m[2], reason: m[3].trim() },
    ],
  },
  {
    pattern: /^error: option '(.+?)' argument missing$/,
    build: m => [`error: option '{option}' argument missing`, { option: m[1] }],
  },
  {
    pattern: /^error: required option '(.+?)' not specified$/,
    build: m => [`error: required option '{option}' not specified`, { option: m[1] }],
  },
  {
    pattern: /^error: option '(.+?)' value '(.+?)' from env '(.+?)' is invalid\.$/,
    build: m => [
      `error: option '{option}' value '{value}' from env '{env}' is invalid.`,
      { option: m[1], value: m[2], env: m[3] },
    ],
  },
  {
    pattern: /^error: command-argument value '(.+?)' is invalid for argument '(.+?)'\.$/,
    build: m => [
      `error: command-argument value '{value}' is invalid for argument '{name}'.`,
      { value: m[1], name: m[2] },
    ],
  },
  // Last resort: localize the marker and keep whatever commander produced after it.
  { pattern: /^error: (.*)$/, build: m => [`error: {message}`, { message: m[1] }] },
];

/**
 * Localize a commander-generated error message.
 *
 * @param message - Raw text commander is about to write to stderr.
 * @returns The localized message, or `message` unchanged when the locale is not Simplified
 * Chinese or the shape is not recognised.
 */
export function localizeCommanderError(message: string): string {
  if (getLocale() === "en") return message;
  // commander appends `\n` before handing the string over, and JavaScript's `$` (unlike a
  // line-anchored regex) matches only at the end of input — so the newline is split off first
  // and put back afterwards, otherwise no rule matches and the English text would leak through.
  const trailing = /\n*$/.exec(message)?.[0] ?? "";
  const body = trailing === "" ? message : message.slice(0, message.length - trailing.length);
  for (const { pattern, build } of RULES) {
    const match = body.match(pattern);
    if (match === null) continue;
    const [source, params] = build(match);
    return t(source, params) + trailing;
  }
  return message;
}

const customErrorOutput = new WeakSet<object>();

/**
 * Marks a command that installs its own `outputError` handler so
 * {@link installCommanderErrorLocalization} does not overwrite it.
 */
export function markCustomErrorOutput(command: object): void {
  customErrorOutput.add(command);
}

/**
 * Installs localized error output on `root` and every command beneath it.
 *
 * commander only copies `_outputConfiguration` onto commands created with `.command()`;
 * commands registered through `addCommand()` keep their own, so the whole tree is visited.
 */
export function installCommanderErrorLocalization(root: CommandUnknownOpts): void {
  const visit = (command: CommandUnknownOpts): void => {
    if (!customErrorOutput.has(command)) {
      command.configureOutput({
        outputError: (str, write) => write(localizeCommanderError(str)),
      });
    }
    for (const child of command.commands) {
      visit(child as unknown as CommandUnknownOpts);
    }
  };
  visit(root);
}
